#!/bin/sh
sxhkd &
picom &
dropbox &
~/.config/polybar/launch.sh dark &

bspc monitor DP-4 -d I II III IV V
bspc monitor DP-0 -d VI VII VIII IX X

bspc config border_width    2
bspc config window_gap      10

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config pointer_modifier    mod4
bspc config pointer_action1     move
bspc config pointer_action2     resize_side
bspc config pointer_action3     resize_corner

bspc config normal_border_color     "#2E3440"
bspc config active_border_color     "#88C0D0"
bspc config focused_border_color    "#5E81AC"
bspc config presel_feedback_color   "#81A1C1"
bspc config urgent_border_color     "#BF616A"

bspc rule -a Gimp             state=floating follow=on
# bspc rule -a firefox          desktop='^2'
# bspc rule -a Chromium         desktop='^2'
# bspc rule -a Vivaldi-stable   desktop='^2'
bspc rule -a mplayer2         state=floating
bspc rule -a Qalculate-gtk    state=floating
bspc rule -a Kupfer.py        focus=on
bspc rule -a Screenkey        manage=off
bspc rule -a Emacs            state=tiled
